// Save this as: lib/helpers/smart_search_helper.dart

class SmartSearchHelper {
  // Simple translation pairs - add more as needed
  static const Map<String, String> translations = {
    // English to Arabic
    // Vehicles (Car Brands)
    'alfa romeo': 'ألفا روميو',
    'aston martin': 'أستون مارتن',
    'audi': 'أودي',
    'avatr': 'أفاتار',
    'bmw': 'بي إم دبليو',
    'byd': 'بي واي دي',
    'baic': 'بايك',
    'bentley': 'بنتلي',
    'bestune': 'بيستون',
    'brilliance': 'بريليانس',
    'bugatti': 'بوغاتي',
    'buick': 'بيوك',
    'cadillac': 'كاديلاك',
    'chana': 'شانا',
    'changan': 'شانجان',
    'changhe': 'شانغي',
    'chery': 'شيري',
    'chevrolet': 'شيفروليه',
    'chrysler': 'كرايسلر',
    'citroen': 'ستروين',
    'cupra': 'كوبرا',
    'dfsk': 'دي إف إس كي',
    'daewoo': 'دايو',
    'daihatsu': 'دايهاتسو',
    'dodge': 'دودج',
    'faw': 'فاو',
    'ferrari': 'فيراري',
    'fiat': 'فيات',
    'ford': 'فورد',
    'gac': 'جي إيه سي',
    'gmc': 'جي إم سي',
    'geely': 'جيلي',
    'great wall': 'جريت وول',
    'haval': 'هافال',
    'honda': 'هوندا',
    'hummer': 'هامر',
    'hyundai': 'هيونداي',
    'infiniti': 'إنفينيتي',
    'isuzu': 'إيسوزو',
    'jac': 'جاك',
    'jaguar': 'جاكوار',
    'jetour': 'جيتور',
    'jeep': 'جيب',
    'kia': 'كيا',
    'king long': 'كينغ لونغ',
    'lada': 'لادا',
    'lamborghini': 'لامبورغيني',
    'land rover': 'لاند روفر',
    'lexus': 'لكزس',
    'lifan': 'ليفان',
    'lincoln': 'لينكون',
    'lotus': 'لوتس',
    'mg': 'إم جي',
    'mini': 'ميني',
    'maserati': 'مازيراتي',
    'mazda': 'مازدا',
    'mclaren': 'مكلارين',
    'mercedes-benz': 'مرسيدس بنز',
    'mitsubishi': 'ميتسوبيشي',
    'nissan': 'نيسان',
    'opel': 'أوبل',
    'peugeot': 'بيجو',
    'porsche': 'بورش',
    'proton': 'بروتون',
    'renault': 'رينو',
    'rolls royce': 'رولز رويس',
    'senova': 'سينوفا',
    'skoda': 'سكودا',
    'soueast': 'سوايست',
    'speranza': 'سبيرانزا',
    'ssang yong': 'سانج يونغ',
    'subaru': 'سوبارو',
    'suzuki': 'سوزوكي',
    'seat': 'سيات',
    'tesla': 'تيسلا',
    'toyota': 'تويوتا',
    'volkswagen': 'فولكس فاجن',
    'volvo': 'فولفو',
    'xpeng': 'إكس بينغ',
    'xiaomi': 'شاومي',
    'zeekr': 'زيكر',
    'zotye': 'زوتي',
    'other make': 'صنع آخر',
    'acura': 'أكورا',
    'alpine': 'ألباين',
    'aries': 'أريس',
    'asia motors': 'آسيا موتورز',
    'aston martin lagonda': 'أستون مارتن لاغوندا',
    'auburn': 'أوبرن',
    'aurora': 'أورورا',
    'autobacs': 'أوتوباكس',
    'baojun': 'باوجون',
    'barkas': 'باركاس',
    'bedford': 'بيدفورد',
    'bharatbenz': 'بهارات بنز',
    'bolwell': 'بولويل',
    'brabus': 'برابوس',
    'breitling': 'بريتlinge',
    'bristol': 'بريستول',
    'carlsson': 'كارلسون',
    'caterham': 'كاترهام',
    'cheryexeed': 'شيري إكسيد',
    'chevrolet camaro': 'شيفروليه كامارو',
    'chevrolet corvette': 'شيفروليه كورفيت',
    'chrysler 300': 'كرايسلر 300',
    'cord': 'كورد',
    'csepel': 'سيبيل',
    'dacia': 'داسيا',
    'delorean': 'ديلوريان',
    'denza': 'دينزا',
    'desoto': 'ديسوتو',
    'diatto': 'دياتو',
    'dodge charger': 'دودج تشارجر',
    'dodge viper': 'دودج فايبر',
    'eagle': 'إيغل',
    'englon': 'إنجلون',
    'enyaq': 'إينياك',
    'europestar': 'يوروبي ستار',
    'fisker': 'فيسكر',
    'foton': 'فوتون',
    'fs0': 'إف إس صفر',
    'gonow': 'جوناو',
    'haima': 'هايما',
    'holden': 'هولدن',
    'hongqi': 'هونغكي',
    'hsv': 'إتش إس في',
    'hudson': 'هدسون',
    'hummer h1': 'هامر إتش 1',
    'hummer h2': 'هامر إتش 2',
    'hummer h3': 'هامر إتش 3',
    'hummer hx': 'هامر إتش إكس',
    'icml': 'آي سي إم إل',
    'ikea': 'إيكيا',
    'inokom': 'إينوكوم',
    'isdera': 'إيسديرا',
    'italdesign': 'إيطالديزاين',
    'iveco': 'إيفيكو',
    'jensen': 'جنسن',
    'jonway': 'جونواي',
    'joylong': 'جويلونغ',
    'kawei': 'كاوي',
    'kenbo': 'كينبو',
    'koenigsegg': 'كونيغسيغ',
    'lamborghini aventador': 'لامبورغيني أفينتادور',
    'lancia': 'لانشيا',
    'landwind': 'لاندويند',
    'leopard': 'ليوبارد',
    'liebao': 'ليباو',
    'mahindra': 'ماهيندرا',
    'maruti': 'ماروتي',
    'maserati granturismo': 'مازيراتي غرانتوريسمو',
    'matra': 'ماترا',
    'maybach': 'مايباخ',
    'mclaren p1': 'مكلارين بي 1',
    'mercury': 'ميركوري',
    'mg rover': 'إم جي روفر',
    'morgan': 'مورغان',
    'naza': 'نازا',
    'noble': 'نوبل',
    'oldsmobile': 'أولدسموبيل',
    'pagani': 'باجاني',
    'panther': 'بانثر',
    'perodua': 'بيرودوا',
    'plymouth': 'بليموث',
    'pontiac': 'بونتياك',
    'porsche cayenne': 'بورش كايين',
    'proton exora': 'بروتون إكسورا',
    'qoros': 'كوروس',
    'ram': 'رام',
    'reliant': 'ريليانت',
    'renault duster': 'رينو دuster',
    'rimac': 'ريماتش',
    'rover': 'روفر',
    'saab': 'سايب',
    'saturn': 'ساتورن',
    'scion': 'ساين',
    'smart': 'سمارت',
    'ssc': 'إس إس سي',
    'studebaker': 'ستوديباكر',
    'tata': 'تاتا',
    'tianye': 'تياني',
    'triumph': 'ترايومف',
    'tvrs': 'تي في آر إس',
    'venucia': 'فينوشيا',
    'wiesmann': 'فيسمان',
    'willys': 'ويليس',
    'wuling': 'وولينغ',
    'xev': 'إكس إي في',
    'zastava': 'زاستافا',

    // Mobiles & Tablets (Phone Brands)
    'apple': 'أبل',
    'samsung': 'سامسونج',
    'huawei': 'هواوي',
    'oppo': 'أوبو',
    'vivo': 'فيفو',
    'realme': 'ريلمي',
    'nokia': 'نوكيا',
    'sony': 'سوني',
    'motorola': 'موتورولا',
    'lg': 'ال جي',
    'lenovo': 'لينوفو',
    'asus': 'أسوس',
    'tecno': 'تكنو',
    'infinix': 'إنفينكس',
    'oneplus': 'ون بلس',
    'google': 'جوجل',
    'htc': 'اچ تي سي',
    'alcatel': 'ألكاتيل',
    'blackberry': 'بلاك بيري',
    'caterpillar': 'كاتربيلر',
    'cat': 'كات',
    'coolpad': 'كول باد',
    'doogee': 'دووجي',
    'elephone': 'إليكترون',
    'energizer': 'إنرجايزر',
    'fairphone': 'فير فون',
    'gigabyte': 'جيجابايت',
    'gionee': 'جيوني',
    'hisense': 'هيسينس',
    'honor': 'هونر',
    'jio': 'جيو',
    'katagon': 'كاتاجون',
    'lava': 'لافا',
    'leeco': 'لييكو',
    'lyf': 'لايف',
    'meizu': 'ميزو',
    'micromax': 'مايكروماكس',
    'nothing': 'نثينج',
    'oukitel': 'أوكيتيل',
    'panasonic': 'باناسونيك',
    'philips': 'فيليبس',
    'poco': 'بوكو',
    'redmi': 'ريدمی',
    'sharp': 'شارب',
    'symphony': 'سيمفوني',
    'tcl': 'تي سي إل',
    'tecno camon': 'تكنو كامون',
    'telit': 'تيليت',
    'thl': 'تي إتش إل',
    'toshiba': 'طوشيبا',
    'ulefone': 'أوليفون',
    'vkworld': 'في كي ورلد',
    'vsmart': 'في سмарٹ',
    'wiko': 'ويكو',
    'xolo': 'كسولو',
    'yu': 'يو',
    'zopo': 'زوبو',
    'zte': 'زد تي إي',
    'archos': 'آركوس',
    'blu': 'بلو',
    'bq': 'بي كيو',
    'celkon': 'سيلكون',
    'condor': 'كوندور',
    'crosscall': 'كروس كال',
    'essential': 'إيسينشيال',
    'garmin': 'جارمن',
    'haier': 'هير',
    'ikoala': 'إيكوالا',
    'itel': 'آيتيل',
    'karbonn': 'كاربون',
    'kyocera': 'كيوسيرا',
    'landvo': 'لاندفو',
    'maxwest': 'ماكس وست',
    'matsun': 'ماتسون',
    'nubia': 'نوبيا',
    'palm': 'بالم',
    'planet': 'بلانت',
    'plum': 'بلوم',
    'posh': 'بوش',
    'qmobile': 'كيو موبيل',
    'rca': 'آر سي إي',
    'safelink': 'سيف لينك',
    'samsung galaxy': 'سامسونج جالاكسي',
    'siragon': 'سيراجون',
    'sky': 'سكاي',
    'spice': 'سبيس',
    'sugar': 'شوغر',
    'tecno spark': 'تكنو سبارك',
    'telefunken': 'تلفونكن',
    'tinno': 'تينو',
    'titan': 'تيتان',
    'unnecto': 'اونيكتو',
    'vertu': 'فيرتو',
    'vivo y': 'فيفو واي',
    'vodafone': 'فودافون',
    'walton': 'والتن',
    'wileyfox': 'ويلي فوكس',
    'yezz': 'يز',
    'yota': 'يوتا',
    'zen': 'زين',

    // Electronics (Additional Terms)
    'charger': 'شاحن',
    'battery': 'بطارية',
    'headset': 'سماعة رأس',
    'keyboard': 'لوحة مفاتيح',
    'mouse': 'فأرة',
    'monitor': 'شاشة',
    'desktop': 'حاسوب',
    'hard drive': 'قرص صلب',
    'ssd': 'SSD',
    'usb': 'USB',
    'power bank': 'بنك طاقة',
    'bluetooth': 'بلوتوث',
    'wireless': 'لاسلكي',
    'cable': 'كابل',
    'adapter': 'محول',
    'remote': 'ريموت',
    'dvd player': 'مشغل DVD',
    'blu-ray': 'بلو-راي',
    'smart tv': 'تلفزيون ذكي',

    // Home & Living (Additional Terms)
    'mirror': 'مرآة',
    'shelf': 'رف',
    'couch': 'كنبة',
    'mattress': 'ماتريس',
    'pillow': 'وسادة',
    'blanket': 'بطانية',
    'fan': 'مروحة',
    'heater': 'مدفأة',
    'cookware': 'أدوات طبخ',
    'cutlery': 'أدوات مائدة',
    'dishwasher': 'غسالة صحون',
    'oven': 'فرن',
    'grill': 'شواية',
    'vacuum cleaner': 'مكنسة كهربائية',
    'garden furniture': 'أثاث حديقة',

    // Fashion (Additional Terms)
    'skirt': 'تنورة',
    't-shirt': 'تي شيرت',
    'sweater': 'صوفة',
    'jeans': 'جينز',
    'sneakers': 'سنيكرز',
    'boots': 'بوت',
    'handbag': 'حقيبة يد',
    'wallet': 'محفظة',
    'necklace': 'قلادة',
    'bracelet': 'أساور',
    'earrings': 'أقراط',
    'ring': 'خاتم',
    'gloves': 'قفازات',
    'socks': 'جوارب',

    // Hobbies, Music, Art & Books (Additional Terms)
    'drum': 'طبلة',
    'violin': 'كمان',
    'flute': 'ناي',
    'microphone': 'ميكروفون',
    'amplifier': 'مضخم صوت',
    'easel': 'حامل لوحة',
    'canvas': 'لوحة قماش',
    'sketchbook': 'دفتر رسم',
    'novel': 'رواية',
    'textbook': 'كتاب دراسي',
    'comic': 'كوميكس',
    'vinyl': 'فينيل',

    // Pets (Additional Terms)
    'rabbit': 'أرنب',
    'hamster': 'هامستر',
    'turtle': 'سلحفاة',
    'cage': 'قفص',
    'food bowl': 'وعاء طعام',
    'leash': 'حبل',
    'collar': 'طوق',

    // Business & Industrial (Additional Terms)
    'generator': 'مولد كهرباء',
    'crane': 'رافعة',
    'drill': 'دريل',
    'saw': 'منشار',
    'welding machine': 'آلة لحام',
    'factory': 'مصنع',
    'warehouse equipment': 'معدات مستودعات',

    // Services (Additional Terms)
    'repair': 'إصلاح',
    'maintenance': 'صيانة',
    'installation': 'تركيب',
    'consulting': 'استشارات',
    'design': 'تصميم',
    'photography': 'تصوير',
    'translation': 'ترجمة',
    'security': 'أمن',

    // Jobs (Additional Terms)
    'designer': 'مصمم',
    'developer': 'مطور',
    'architect': 'مهندس معماري',
    'pharmacist': 'صيدلي',
    'dentist': 'طبيب أسنان',
    'veterinarian': 'بيطري',
    'cashier': 'كاشير',
    'guard': 'حارس',

    // General Terms
    'available': 'متوفر',
    'sold': 'مباع',
    'negotiable': 'قابل للتفاوض',
    'discount': 'تخفيض',
    'offer': 'عرض',
    'trade': 'تبادل',
    'auction': 'مزاد',
    'warranty': 'ضمان',
    'return': 'مرتجع',
    'shipping': 'شحن',
    'local': 'محلي',
    'international': 'دولي',
    'original': 'أصلي',
    'copy': 'نسخة',
    'limited edition': 'طبعة محدودة',
    'small': 'صغير',
    'medium': 'متوسط',
    'large': 'كبير',
    'extra large': 'جيجا',
    'black': 'أسود',
    'white': 'أبيض',
    'red': 'أحمر',
    'blue': 'أزرق',
    'green': 'أخضر',
    'yellow': 'أصفر',
    'pink': 'وردي',
    'gold': 'ذهبي',
    'silver': 'فضي',
    'leather': 'جلد',
    'cotton': 'قطن',
    'wool': 'صوف',
    'silk': 'حرير',
    'plastic': 'بلاستيك',
    'metal': 'معدن',
    'wood': 'خشب',

    // Locations in Egypt (Expanded)
    'cairo': 'القاهرة',
    'alexandria': 'اسكندرية',
    'giza': 'الجيزة',
    'luxor': 'الأقصر',
    'aswan': 'أسوان',
    'sharm el sheikh': 'شرم الشيخ',
    'hurghada': 'الغردقة',
    'mansoura': 'المنصورة',
    'tanta': 'طنطا',
    'port said': 'بورسعيد',
    'suez': 'السويس',
    'ismailia': 'الإسماعيلية',
    'fayoum': 'الفيوم',
    'minya': 'المنيا',
    'assiut': 'أسيوط',
    'qena': 'قنا',
    'sohag': 'سوهاج',
    'beni suef': 'بني سويف',
    'damietta': 'دمياط',
    'kafr el sheikh': 'كفر الشيخ',
    'beheira': 'البحيرة',
    'matrouh': 'مطروح',
    'red sea': 'البحر الأحمر',
    'new cairo': 'القاهرة الجديدة',
    '6th of october': 'ستة أكتوبر',
    'nasr city': 'مدينة نصر',
    'heliopolis': 'مصر الجديدة',
    'maadi': 'المعادي',
    'zamalek': 'الزمالك',
    'downtown': 'وسط البلد',
    'garden city': 'الحدائق',

    // Arabic to English (reverse)
    // Vehicles (Car Brands)
    'ألفا روميو': 'alfa romeo',
    'أستون مارتن': 'aston martin',
    'أودي': 'audi',
    'أفاتار': 'avatr',
    'بي إم دبليو': 'bmw',
    'بي واي دي': 'byd',
    'بايك': 'baic',
    'بنتلي': 'bentley',
    'بيستون': 'bestune',
    'بريليانس': 'brilliance',
    'بوغاتي': 'bugatti',
    'بيوك': 'buick',
    'كاديلاك': 'cadillac',
    'شانا': 'chana',
    'شانجان': 'changan',
    'شانغي': 'changhe',
    'شيري': 'chery',
    'شيفروليه': 'chevrolet',
    'كرايسلر': 'chrysler',
    'ستروين': 'citroen',
    'كوبرا': 'cupra',
    'دي إف إس كي': 'dfsk',
    'دايو': 'daewoo',
    'دايهاتسو': 'daihatsu',
    'دودج': 'dodge',
    'فاو': 'faw',
    'فيراري': 'ferrari',
    'فيات': 'fiat',
    'فورد': 'ford',
    'جي إيه سي': 'gac',
    'جي إم سي': 'gmc',
    'جيلي': 'geely',
    'جريت وول': 'great wall',
    'هافال': 'haval',
    'هوندا': 'honda',
    'هامر': 'hummer',
    'هيونداي': 'hyundai',
    'إنفينيتي': 'infiniti',
    'إيسوزو': 'isuzu',
    'جاك': 'jac',
    'جاكوار': 'jaguar',
    'جيتور': 'jetour',
    'جيب': 'jeep',
    'كيا': 'kia',
    'كينغ لونغ': 'king long',
    'لادا': 'lada',
    'لامبورغيني': 'lamborghini',
    'لاند روفر': 'land rover',
    'لكزس': 'lexus',
    'ليفان': 'lifan',
    'لينكون': 'lincoln',
    'لوتس': 'lotus',
    'إم جي': 'mg',
    'ميني': 'mini',
    'مازيراتي': 'maserati',
    'مازدا': 'mazda',
    'مكلارين': 'mclaren',
    'مرسيدس بنز': 'mercedes-benz',
    'ميتسوبيشي': 'mitsubishi',
    'نيسان': 'nissan',
    'أوبل': 'opel',
    'بيجو': 'peugeot',
    'بورش': 'porsche',
    'بروتون': 'proton',
    'رينو': 'renault',
    'رولز رويس': 'rolls royce',
    'سينوفا': 'senova',
    'سكودا': 'skoda',
    'سوايست': 'soueast',
    'سبيرانزا': 'speranza',
    'سانج يونغ': 'ssang yong',
    'سوبارو': 'subaru',
    'سوزوكي': 'suzuki',
    'سيات': 'seat',
    'تيسلا': 'tesla',
    'تويوتا': 'toyota',
    'فولكس فاجن': 'volkswagen',
    'فولفو': 'volvo',
    'إكس بينغ': 'xpeng',
    'شاومي': 'xiaomi',
    'زيكر': 'zeekr',
    'زوتي': 'zotye',
    'صنع آخر': 'other make',
    'أكورا': 'acura',
    'ألباين': 'alpine',
    'أريس': 'aries',
    'آسيا موتورز': 'asia motors',
    'أستون مارتن لاغوندا': 'aston martin lagonda',
    'أوبرن': 'auburn',
    'أورورا': 'aurora',
    'أوتوباكس': 'autobacs',
    'باوجون': 'baojun',
    'باركاس': 'barkas',
    'بيدفورد': 'bedford',
    'بهارات بنز': 'bharatbenz',
    'بولويل': 'bolwell',
    'برابوس': 'brabus',
    'بريتlinge': 'breitling',
    'بريستول': 'bristol',
    'كارلسون': 'carlsson',
    'كاترهام': 'caterham',
    'شيري إكسيد': 'cheryexeed',
    'شيفروليه كامارو': 'chevrolet camaro',
    'شيفروليه كورفيت': 'chevrolet corvette',
    'كرايسلر 300': 'chrysler 300',
    'كورد': 'cord',
    'سيبيل': 'csepel',
    'داسيا': 'dacia',
    'ديلوريان': 'delorean',
    'دينزا': 'denza',
    'ديسوتو': 'desoto',
    'دياتو': 'diatto',
    'دودج تشارجر': 'dodge charger',
    'دودج فايبر': 'dodge viper',
    'إيغل': 'eagle',
    'إنجلون': 'englon',
    'إينياك': 'enyaq',
    'يوروبي ستار': 'europestar',
    'فيسكر': 'fisker',
    'فوتون': 'foton',
    'إف إس صفر': 'fs0',
    'جوناو': 'gonow',
    'هايما': 'haima',
    'هولدن': 'holden',
    'هونغكي': 'hongqi',
    'إتش إس في': 'hsv',
    'هدسون': 'hudson',
    'هامر إتش 1': 'hummer h1',
    'هامر إتش 2': 'hummer h2',
    'هامر إتش 3': 'hummer h3',
    'هامر إتش إكس': 'hummer hx',
    'آي سي إم إل': 'icml',
    'إيكيا': 'ikea',
    'إينوكوم': 'inokom',
    'إيسديرا': 'isdera',
    'إيطالديزاين': 'italdesign',
    'إيفيكو': 'iveco',
    'جنسن': 'jensen',
    'جونواي': 'jonway',
    'جويلونغ': 'joylong',
    'كاوي': 'kawei',
    'كينبو': 'kenbo',
    'كونيغسيغ': 'koenigsegg',
    'لامبورغيني أفينتادور': 'lamborghini aventador',
    'لانشيا': 'lancia',
    'لاندويند': 'landwind',
    'ليوبارد': 'leopard',
    'ليباو': 'liebao',
    'ماهيندرا': 'mahindra',
    'ماروتي': 'maruti',
    'مازيراتي غرانتوريسمو': 'maserati granturismo',
    'ماترا': 'matra',
    'مايباخ': 'maybach',
    'مكلارين بي 1': 'mclaren p1',
    'ميركوري': 'mercury',
    'إم جي روفر': 'mg rover',
    'مورغان': 'morgan',
    'نازا': 'naza',
    'نوبل': 'noble',
    'أولدسموبيل': 'oldsmobile',
    'باجاني': 'pagani',
    'بانثر': 'panther',
    'بيرودوا': 'perodua',
    'بليموث': 'plymouth',
    'بونتياك': 'pontiac',
    'بورش كايين': 'porsche cayenne',
    'بروتون إكسورا': 'proton exora',
    'كوروس': 'qoros',
    'رام': 'ram',
    'ريليانت': 'reliant',
    'رينو دuster': 'renault duster',
    'ريماتش': 'rimac',
    'روفر': 'rover',
    'سايب': 'saab',
    'ساتورن': 'saturn',
    'ساين': 'scion',
    'سمارت': 'smart',
    'إس إس سي': 'ssc',
    'ستوديباكر': 'studebaker',
    'تاتا': 'tata',
    'تياني': 'tianye',
    'ترايومف': 'triumph',
    'تي في آر إس': 'tvrs',
    'فينوشيا': 'venucia',
    'فيسمان': 'wiesmann',
    'ويليس': 'willys',
    'وولينغ': 'wuling',
    'إكس إي في': 'xev',
    'زاستافا': 'zastava',

    // Mobiles & Tablets (Phone Brands)
    'أبل': 'apple',
    'سامسونج': 'samsung',

    'هواوي': 'huawei',
    'أوبو': 'oppo',
    'فيفو': 'vivo',
    'ريلمي': 'realme',
    'نوكيا': 'nokia',
    'سوني': 'sony',
    'موتورولا': 'motorola',
    'ال جي': 'lg',
    'لينوفو': 'lenovo',
    'أسوس': 'asus',
    'تكنو': 'tecno',
    'إنفينكس': 'infinix',
    'ون بلس': 'oneplus',
    'جوجل': 'google',
    'اچ تي سي': 'htc',
    'ألكاتيل': 'alcatel',
    'بلاك بيري': 'blackberry',
    'كاتربيلر': 'caterpillar',
    'كات': 'cat',
    'كول باد': 'coolpad',
    'دووجي': 'doogee',
    'إليكترون': 'elephone',
    'إنرجايزر': 'energizer',
    'فير فون': 'fairphone',
    'جيجابايت': 'gigabyte',
    'جيوني': 'gionee',
    'هيسينس': 'hisense',
    'هونر': 'honor',
    'جيو': 'jio',
    'كاتاجون': 'katagon',
    'لافا': 'lava',
    'لييكو': 'leeco',
    'لايف': 'lyf',
    'ميزو': 'meizu',
    'مايكروماكس': 'micromax',
    'نثينج': 'nothing',
    'أوكيتيل': 'oukitel',
    'باناسونيك': 'panasonic',
    'فيليبس': 'philips',
    'بوكو': 'poco',
    'ريدمی': 'redmi',
    'شارب': 'sharp',
    'سيمفوني': 'symphony',
    'تي سي إل': 'tcl',
    'تكنو كامون': 'tecno camon',
    'تيليت': 'telit',
    'تي إتش إل': 'thl',
    'طوشيبا': 'toshiba',
    'أوليفون': 'ulefone',
    'في كي ورلد': 'vkworld',
    'في سمرٹ': 'vsmart',
    'ويكو': 'wiko',
    'كسولو': 'xolo',
    'يو': 'yu',
    'زوبو': 'zopo',
    'زد تي إي': 'zte',
    'آركوس': 'archos',
    'بلو': 'blu',
    'بي كيو': 'bq',
    'سيلكون': 'celkon',
    'كوندور': 'condor',
    'كروس كال': 'crosscall',
    'إيسينشيال': 'essential',
    'جارمن': 'garmin',
    'هير': 'haier',
    'إيكوالا': 'ikoala',
    'آيتيل': 'itel',
    'كاربون': 'karbonn',
    'كيوسيرا': 'kyocera',
    'لاندفو': 'landvo',
    'ماكس وست': 'maxwest',
    'ماتسون': 'matsun',
    'نوبيا': 'nubia',
    'بالم': 'palm',
    'بلانت': 'planet',
    'بلوم': 'plum',
    'بوش': 'posh',
    'كيو موبيل': 'qmobile',
    'آر سي إي': 'rca',
    'سيف لينك': 'safelink',
    'سامسونج جالاكسي': 'samsung galaxy',
    'سيراجون': 'siragon',
    'سكاي': 'sky',
    'سبيس': 'spice',
    'شوغر': 'sugar',
    'تكنو سبارك': 'tecno spark',
    'تلفونكن': 'telefunken',
    'تينو': 'tinno',
    'تيتان': 'titan',
    'اونيكتو': 'unnecto',
    'فيرتو': 'vertu',
    'فيفو واي': 'vivo y',
    'فودافون': 'vodafone',
    'والتن': 'walton',
    'ويلي فوكس': 'wileyfox',
    'يز': 'yezz',
    'يوتا': 'yota',
    'زين': 'zen',

    // Electronics (Additional Terms)
    'شاحن': 'charger',
    'بطارية': 'battery',
    'سماعة رأس': 'headset',
    'لوحة مفاتيح': 'keyboard',
    'فأرة': 'mouse',
    'شاشة': 'monitor',
    'حاسوب': 'desktop',
    'قرص صلب': 'hard drive',
    'SSD': 'ssd',
    'USB': 'usb',
    'بنك طاقة': 'power bank',
    'بلوتوث': 'bluetooth',
    'لاسلكي': 'wireless',
    'كابل': 'cable',
    'محول': 'adapter',
    'ريموت': 'remote',
    'مشغل DVD': 'dvd player',
    'بلو-راي': 'blu-ray',
    'تلفزيون ذكي': 'smart tv',

    // Home & Living (Additional Terms)
    'مرآة': 'mirror',
    'رف': 'shelf',
    'كنبة': 'couch',
    'ماتريس': 'mattress',
    'وسادة': 'pillow',
    'بطانية': 'blanket',
    'مروحة': 'fan',
    'مدفأة': 'heater',
    'أدوات طبخ': 'cookware',
    'أدوات مائدة': 'cutlery',
    'غسالة صحون': 'dishwasher',
    'فرن': 'oven',
    'شواية': 'grill',
    'مكنسة كهربائية': 'vacuum cleaner',
    'أثاث حديقة': 'garden furniture',

    // Fashion (Additional Terms)
    'تنورة': 'skirt',
    'تي شيرت': 't-shirt',
    'صوفة': 'sweater',
    'جينز': 'jeans',
    'سنيكرز': 'sneakers',
    'بوت': 'boots',
    'حقيبة يد': 'handbag',
    'محفظة': 'wallet',
    'قلادة': 'necklace',
    'أساور': 'bracelet',
    'أقراط': 'earrings',
    'خاتم': 'ring',
    'قفازات': 'gloves',
    'جوارب': 'socks',

    // Hobbies, Music, Art & Books (Additional Terms)
    'طبلة': 'drum',
    'كمان': 'violin',
    'ناي': 'flute',
    'ميكروفون': 'microphone',
    'مضخم صوت': 'amplifier',
    'حامل لوحة': 'easel',
    'لوحة قماش': 'canvas',
    'دفتر رسم': 'sketchbook',
    'رواية': 'novel',
    'كتاب دراسي': 'textbook',
    'كوميكس': 'comic',
    'فينيل': 'vinyl',

    // Pets (Additional Terms)
    'أرنب': 'rabbit',
    'هامستر': 'hamster',
    'سلحفاة': 'turtle',
    'قفص': 'cage',
    'وعاء طعام': 'food bowl',
    'حبل': 'leash',
    'طوق': 'collar',

    // Business & Industrial (Additional Terms)
    'مولد كهرباء': 'generator',
    'رافعة': 'crane',
    'دريل': 'drill',
    'منشار': 'saw',
    'آلة لحام': 'welding machine',
    'مصنع': 'factory',
    'معدات مستودعات': 'warehouse equipment',

    // Services (Additional Terms)
    'إصلاح': 'repair',
    'صيانة': 'maintenance',
    'تركيب': 'installation',
    'استشارات': 'consulting',
    'تصميم': 'design',
    'تصوير': 'photography',
    'ترجمة': 'translation',
    'أمن': 'security',

    // Jobs (Additional Terms)
    'مصمم': 'designer',
    'مطور': 'developer',
    'مهندس معماري': 'architect',
    'صيدلي': 'pharmacist',
    'طبيب أسنان': 'dentist',
    'بيطري': 'veterinarian',
    'كاشير': 'cashier',
    'حارس': 'guard',

    // General Terms
    'متوفر': 'available',
    'مباع': 'sold',
    'قابل للتفاوض': 'negotiable',
    'تخفيض': 'discount',
    'عرض': 'offer',
    'تبادل': 'trade',
    'مزاد': 'auction',
    'ضمان': 'warranty',
    'مرتجع': 'return',
    'شحن': 'shipping',
    'محلي': 'local',
    'دولي': 'international',
    'أصلي': 'original',
    'نسخة': 'copy',
    'طبعة محدودة': 'limited edition',
    'صغير': 'small',
    'متوسط': 'medium',
    'كبير': 'large',
    'جيجا': 'extra large',
    'أسود': 'black',
    'أبيض': 'white',
    'أحمر': 'red',
    'أزرق': 'blue',
    'أخضر': 'green',
    'أصفر': 'yellow',
    'وردي': 'pink',
    'ذهبي': 'gold',
    'فضي': 'silver',
    'جلد': 'leather',
    'قطن': 'cotton',
    'صوف': 'wool',
    'حرير': 'silk',
    'بلاستيك': 'plastic',
    'معدن': 'metal',
    'خشب': 'wood',

    // Locations in Egypt (Expanded)
    'القاهرة': 'cairo',
    'اسكندرية': 'alexandria',
    'الجيزة': 'giza',
    'الأقصر': 'luxor',
    'أسوان': 'aswan',
    'شرم الشيخ': 'sharm el sheikh',
    'الغردقة': 'hurghada',
    'المنصورة': 'mansoura',
    'طنطا': 'tanta',
    'بورسعيد': 'port said',
    'السويس': 'suez',
    'الإسماعيلية': 'ismailia',
    'الفيوم': 'fayoum',
    'المنيا': 'minya',
    'أسيوط': 'assiut',
    'قنا': 'qena',
    'سوهاج': 'sohag',
    'بني سويف': 'beni suef',
    'دمياط': 'damietta',
    'كفر الشيخ': 'kafr el sheikh',
    'البحيرة': 'beheira',
    'مطروح': 'matrouh',
    'البحر الأحمر': 'red sea',
    'القاهرة الجديدة': 'new cairo',
    'ستة أكتوبر': '6th of october',
    'مدينة نصر': 'nasr city',
    'مصر الجديدة': 'heliopolis',
    'المعادي': 'maadi',
    'الزمالك': 'zamalek',
    'وسط البلد': 'downtown',
    'الحدائق': 'garden city',
  };

  // Letter mappings for keyboard mix-ups
  static String getBothLanguages(String query) {
    String cleanQuery = query.toLowerCase().trim();

    // Check if we have a direct translation
    if (translations.containsKey(cleanQuery)) {
      String translation = translations[cleanQuery]!;
      return '$query $translation';
    }

    // Check for partial matches in multi-word queries
    List<String> words = cleanQuery.split(' ');
    Set<String> allTerms = {query}; // Start with original query

    for (String word in words) {
      if (translations.containsKey(word)) {
        allTerms.add(translations[word]!);
      }
    }

    return allTerms.join(' ');
  }
}
