/// Generated file. Do not edit.
/// This file is generated by the iFlutter
library;

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'list_and_life';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String IC_BUSSINESS_ICON =
      'assets/category/ic_bussiness_icon.png';
  static const String IC_ELECTRONICS_ICONS =
      'assets/category/ic_electronics_icons.png';
  static const String IC_FASHION = 'assets/category/ic_fashion.png';
  static const String IC_HOBBY_ICONS = 'assets/category/ic_hobby_icons.png';
  static const String IC_HOME_AND_LIVING_ICON =
      'assets/category/ic_home_and_living_icon.png';
  static const String IC_HOME_APPLIANCES =
      'assets/category/ic_home_appliances.png';
  static const String IC_HOME_DECOR_GARDEN =
      'assets/category/ic_home_decor_garden.png';
  static const String IC_JOBS_ICON = 'assets/category/ic_jobs_icon.png';
  static const String IC_PETS_ICON = 'assets/category/ic_pets_icon.png';
  static const String IC_PHONE_ICON = 'assets/category/ic_phone_icon.png';
  static const String IC_SERVICE_ICON = 'assets/category/ic_service_icon.png';
  static const String IC_VEHICLE_ICONS = 'assets/category/ic_vehicle_icons.png';
  static const String DUMMY_CAR_FIRST = 'assets/dummy/dummy_car_first.png';
  static const String DUMMY_CAR_IMAGE1 = 'assets/dummy/dummy_car_image1.jpg';
  static const String DUMMY_CAR_IMAGE2 = 'assets/dummy/dummy_car_image2.jpg';
  static const String DUMMY_CAR_IMAGE3 = 'assets/dummy/dummy_car_image3.jpg';
  static const String DUMMY_CAR_IMAGE4 = 'assets/dummy/dummy_car_image4.jpg';
  static const String DUMMY_CAR_SECOUND = 'assets/dummy/dummy_car_secound.png';
  static const String DUMMY_CAR_THIRD = 'assets/dummy/dummy_car_third.png';
  static const String DUMMY_CHAT_IMAGE1 = 'assets/dummy/dummy_chat_image1.png';
  static const String DUMMY_CHAT_IMAGE2 = 'assets/dummy/dummy_chat_image2.png';
  static const String DUMMY_CHAT_IMAGE3 = 'assets/dummy/dummy_chat_image3.png';
  static const String DUMMY_CHAT_IMAGE4 = 'assets/dummy/dummy_chat_image4.png';
  static const String DUMMY_CHAT_IMAGE5 = 'assets/dummy/dummy_chat_image5.png';
  static const String DUMMY_CHAT_IMAGE6 = 'assets/dummy/dummy_chat_image6.png';
  static const String DUMMY_CIRCLE_MAP = 'assets/dummy/dummy_circle_map.png';
  static const String DUMMY_IPHONE_IMAGE1 =
      'assets/dummy/dummy_iphone_image1.jpg';
  static const String DUMMY_IPHONE_IMAGE2 =
      'assets/dummy/dummy_iphone_image2.jpg';
  static const String DUMMY_IPHONE_IMAGE3 =
      'assets/dummy/dummy_iphone_image3.jpg';
  static const String DUMMY_IPHONE_IMAGE4 =
      'assets/dummy/dummy_iphone_image4.jpg';
  static const String DUMMY_MAP_IMAGE = 'assets/dummy/dummy_map_image.png';
  static const String DUMMY_PROFILE = 'assets/dummy/dummy_profile.png';
  static const String IC_ACCESSORIES_IMAGE =
      'assets/icons/ic_accessories_image.png';
  static const String IC_APPLE_ICON = 'assets/icons/ic_apple_icon.png';
  static const String IC_APPLE_LOGO = 'assets/icons/ic_apple_logo.png';
  static const String IC_BELL_ICON = 'assets/icons/ic_bell_icon.png';
  static const String IC_BLOCK_USER = 'assets/icons/ic_block_user.png';
  static const String IC_CALENDER_ICON = 'assets/icons/ic_calender_icon.png';
  static const String IC_CALL_ICON = 'assets/icons/ic_call_icon.png';
  static const String IC_CAR_CAT_IMAGE = 'assets/icons/ic_car_cat_image.png';
  static const String IC_CARDS_ICON = 'assets/icons/ic_cards_icon.png';
  static const String IC_CAT_CAR = 'assets/icons/ic_cat_car.png';
  static const String IC_CAT_CLOTHS = 'assets/icons/ic_cat_cloths.png';
  static const String IC_CAT_FURNITURE = 'assets/icons/ic_cat_furniture.png';
  static const String IC_CAT_LAPTOP = 'assets/icons/ic_cat_laptop.png';
  static const String IC_CAT_MOBILE = 'assets/icons/ic_cat_mobile.png';
  static const String IC_CHAT_ICON = 'assets/icons/ic_chat_icon.png';
  static const String IC_CLOTHES_CAT_IMGE =
      'assets/icons/ic_clothes_cat_imge.png';
  static const String IC_CONGRATULATION_IMAGE =
      'assets/icons/ic_congratulation_image.png';
  static const String IC_DELETE_ACCOUNT = 'assets/icons/ic_delete_account.png';
  static const String IC_FILTER_ICON = 'assets/icons/ic_filter_icon.png';
  static const String IC_FURNITURE_CAT_IMGE =
      'assets/icons/ic_furniture_cat_imge.png';
  static const String IC_GEAR_ICON = 'assets/icons/ic_gear_icon.png';
  static const String IC_GOOGLE_ICON = 'assets/icons/ic_google_icon.png';
  static const String IC_GOOGLE_LOGO = 'assets/icons/ic_google_logo.png';
  static const String IC_IMAGE_PLACEHOLDER =
      'assets/icons/ic_image_placeholder.png';
  static const String IC_ITEM_LOCATION = 'assets/icons/ic_item_location.png';
  static const String IC_LAPTOP_CAT_IMGE =
      'assets/icons/ic_laptop_cat_imge.png';
  static const String IC_LOACTION_ICON = 'assets/icons/ic_loaction_icon.png';
  static const String IC_LOCATION_PIN = 'assets/icons/ic_location_pin.png';
  static const String IC_LOCK_LOGIN = 'assets/icons/ic_lock_login.png';
  static const String IC_LOGOUT = 'assets/icons/ic_logout.png';
  static const String IC_LOGOUT_ICON = 'assets/icons/ic_logout_icon.png';
  static const String IC_MOBILE_CAT_IMGE =
      'assets/icons/ic_mobile_cat_imge.png';
  static const String IC_NO_WIFI = 'assets/icons/ic_no_wifi.png';
  static const String IC_NOTIFICATION = 'assets/icons/ic_notification.png';
  static const String IC_PETROL_ICON = 'assets/icons/ic_petrol_icon.png';
  static const String IC_PRIVCY_POLICY = 'assets/icons/ic_privcy_policy.png';
  static const String IC_PROFILE = 'assets/icons/ic_profile.png';
  static const String IC_REPORT_USER = 'assets/icons/ic_report_user.png';
  static const String IC_SPEED_ICON = 'assets/icons/ic_speed_icon.png';
  static const String IC_T_AND_C = 'assets/icons/ic_t_and_c.png';
  static const String IC_TABLET_IMAGE = 'assets/icons/ic_tablet_image.png';
  static const String IC_USER_ICON = 'assets/icons/ic_user_icon.png';
  static const String IC_WALLET_ICON = 'assets/icons/ic_wallet_icon.png';
  static const String IC_WHATSAPP_ICON = 'assets/icons/ic_whatsapp_icon.png';
  static const String APP_LOGO = 'assets/images/app_logo.png';
  static const String LOCATION_PERMISSION_ILLUSTRATIONS =
      'assets/images/location_permission_illustrations.png';
  static const String ON_BOARD_FIRST = 'assets/images/on_board_first.png';
  static const String ON_BOARD_SECOND = 'assets/images/on_board_second.png';
  static const String ON_BOARD_THIRD = 'assets/images/on_board_third.png';
  static const String SPLASH = 'assets/images/splash.png';
  static const String AUTH_REQUIRED_LOTTIE =
      'assets/lottie_jsons/auth_required_lottie.json';
  static const String DELETE_LOTTIE = 'assets/lottie_jsons/delete_lottie.json';
  static const String EMPTY_LOTTIE = 'assets/lottie_jsons/empty_lottie.json';
  static const String ERROR_LOTTIE = 'assets/lottie_jsons/error_lottie.json';
  static const String LOGOUT_LOTTIE_FILE =
      'assets/lottie_jsons/logout_lottie_file.json';
  static const String NO_IMAGE_LOTTIE =
      'assets/lottie_jsons/no_image_lottie.json';
  static const String NO_NOTIFICATION_LOTTIE =
      'assets/lottie_jsons/no_notification_lottie.json';
  static const String PAGE_NOT_FOUND =
      'assets/lottie_jsons/page_not_found.json';
  static const String SIGNOUT_ANIMATION =
      'assets/lottie_jsons/signout_animation.json';
  static const String TICK_MARK_LOTTIE =
      'assets/lottie_jsons/tick_mark_lottie.json';
  static const String TIMEUP_LOTTIE = 'assets/lottie_jsons/timeup_lottie.json';
  static const String VERIFY_OTP_LOTTIE =
      'assets/lottie_jsons/verify_otp_lottie.json';
}
