/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'list_and_life';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String DUMMY_IPHONE_IMAGE1 =
      'assets/dummy/dummy_iphone_image1.jpg';
  static const String DUMMY_IPHONE_IMAGE2 =
      'assets/dummy/dummy_iphone_image2.jpg';
  static const String DUMMY_IPHONE_IMAGE3 =
      'assets/dummy/dummy_iphone_image3.jpg';
  static const String DUMMY_IPHONE_IMAGE4 =
      'assets/dummy/dummy_iphone_image4.jpg';
  static const String DUMMY_PROFILE = 'assets/dummy/dummy_profile.png';
  static const String IC_APPLE_ICON = 'assets/icons/ic_apple_icon.png';
  static const String IC_BELL_ICON = 'assets/icons/ic_bell_icon.png';
  static const String IC_CALL_ICON = 'assets/icons/ic_call_icon.png';
  static const String IC_CAT_CAR = 'assets/icons/ic_cat_car.png';
  static const String IC_CAT_CLOTHS = 'assets/icons/ic_cat_cloths.png';
  static const String IC_CAT_FURNITURE = 'assets/icons/ic_cat_furniture.png';
  static const String IC_CAT_LAPTOP = 'assets/icons/ic_cat_laptop.png';
  static const String IC_CAT_MOBILE = 'assets/icons/ic_cat_mobile.png';
  static const String IC_CHAT_ICON = 'assets/icons/ic_chat_icon.png';
  static const String IC_DELETE_ACCOUNT = 'assets/icons/ic_delete_account.png';
  static const String IC_FILTER_ICON = 'assets/icons/ic_filter_icon.png';
  static const String IC_GOOGLE_ICON = 'assets/icons/ic_google_icon.png';
  static const String IC_IMAGE = 'assets/icons/ic_image.png';
  static const String IC_ITEM_LOCATION = 'assets/icons/ic_item_location.png';
  static const String IC_LOGOUT = 'assets/icons/ic_logout.png';
  static const String IC_LOGOUT_ICON = 'assets/icons/ic_logout_icon.png';
  static const String IC_NO_WIFI = 'assets/icons/ic_no_wifi.png';
  static const String IC_NOTIFICATION = 'assets/icons/ic_notification.png';
  static const String IC_PRIVCY_POLICY = 'assets/icons/ic_privcy_policy.png';
  static const String IC_PROFILE = 'assets/icons/ic_profile.png';
  static const String IC_T_AND_C = 'assets/icons/ic_t_and_c.png';
  static const String IC_WHATSAPP_ICON = 'assets/icons/ic_whatsapp_icon.png';
  static const String APP_LOGO = 'assets/images/app_logo.png';
  static const String LOCATION_PERMISSION_ILLUSTRATIONS =
      'assets/images/location_permission_illustrations.png';
  static const String ON_BOARD_FIRST = 'assets/images/on_board_first.png';
  static const String ON_BOARD_SECOND = 'assets/images/on_board_second.png';
  static const String ON_BOARD_THIRD = 'assets/images/on_board_third.png';
  static const String SPLASH = 'assets/images/splash.png';
  static const String DELETE_LOTTIE = 'assets/lottie_jsons/delete_lottie.json';
  static const String EMPTY_LOTTIE = 'assets/lottie_jsons/empty_lottie.json';
  static const String ERROR_LOTTIE = 'assets/lottie_jsons/error_lottie.json';
  static const String LOGOUT_LOTTIE_FILE =
      'assets/lottie_jsons/logout_lottie_file.json';
  static const String NO_IMAGE_LOTTIE =
      'assets/lottie_jsons/no_image_lottie.json';
  static const String NO_NOTIFICATION_LOTTIE =
      'assets/lottie_jsons/no_notification_lottie.json';
  static const String PAGE_NOT_FOUND =
      'assets/lottie_jsons/page_not_found.json';
  static const String SIGNOUT_ANIMATION =
      'assets/lottie_jsons/signout_animation.json';
  static const String TICK_MARK_LOTTIE =
      'assets/lottie_jsons/tick_mark_lottie.json';
  static const String TIMEUP_LOTTIE = 'assets/lottie_jsons/timeup_lottie.json';
  static const String VERIFY_OTP_LOTTIE =
      'assets/lottie_jsons/verify_otp_lottie.json';
}
