name: ccp_dialog
description: CCP Dialog package for showing a country code, flag , currency and currencyISO in Dialog and Bottom sheet.
version: 1.0.3
homepage: https://github.com/sharmajatin1997/ccp_dialog

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - flag/

