// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFB1JQ1oOHV2CVJI35EZNK_IdGtGOu0NA',
    appId: '1:349423978681:android:4a584bce7167e883f33368',
    messagingSenderId: '349423978681',
    projectId: 'list-and-life',
    storageBucket: 'list-and-life.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkdLVx_W737dq6DcqKjsswIJ9LgBet5WQ',
    appId: '1:349423978681:ios:4cd013bef1ea3d07f33368',
    messagingSenderId: '349423978681',
    projectId: 'list-and-life',
    storageBucket: 'list-and-life.appspot.com',
    androidClientId: '349423978681-bq6js869ld4l74f148hps0b34ql241f8.apps.googleusercontent.com',
    iosClientId: '349423978681-js9aqmag1bjvutrll786mmdp9tegfn9f.apps.googleusercontent.com',
    iosBundleId: 'com.live.listorlife',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8LyUM4IHrPfy3h6Lie_PiA-S8j_lGYfo',
    appId: '1:349423978681:web:99209918ae303372f33368',
    messagingSenderId: '349423978681',
    projectId: 'list-and-life',
    authDomain: 'list-and-life.firebaseapp.com',
    storageBucket: 'list-and-life.appspot.com',
  );

}