// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFB1JQ1oOHV2CVJI35EZNK_IdGtGOu0NA',
    appId: '1:349423978681:android:d4dc7090156f838cf33368',
    messagingSenderId: '349423978681',
    projectId: 'list-and-life',
    storageBucket: 'list-and-life.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkdLVx_W737dq6DcqKjsswIJ9LgBet5WQ',
    appId: '1:349423978681:ios:fd5a2781c53e724ff33368',
    messagingSenderId: '349423978681',
    projectId: 'list-and-life',
    storageBucket: 'list-and-life.appspot.com',
    androidClientId: '349423978681-n43e63b2n0mn6vmv4mo7469bvlg08f0j.apps.googleusercontent.com',
    iosClientId: '349423978681-3mv3ihrm2mjgh5sdti60us3093h2ksjh.apps.googleusercontent.com',
    iosBundleId: 'com.dev.listorlife',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8LyUM4IHrPfy3h6Lie_PiA-S8j_lGYfo',
    appId: '1:349423978681:web:99209918ae303372f33368',
    messagingSenderId: '349423978681',
    projectId: 'list-and-life',
    authDomain: 'list-and-life.firebaseapp.com',
    storageBucket: 'list-and-life.appspot.com',
  );

}